version: "3.1"
services:

    redis:
      image: redis:5.0.9-alpine
      container_name: laravel-graphql-skeleton-redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ../database/data/redis:/data

    mysql:
      image: mysql:5.7.28
      container_name: laravel-graphql-skeleton-mysql
      working_dir: /application
      volumes:
        - ../database/data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "${DB_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-graphql-skeleton-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${WEB_PORT}:80"

    php-fpm:
      build: php-fpm
      container_name: laravel-graphql-skeleton-php-fpm
      working_dir: /application
      volumes:
        - ../:/application

